# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "51877ece492ee8373a064bac89091cc8"
name = "Hubcodespace Sitemap - DEV"
handle = "hubcodespace-sitemap-builder-dev"
application_url = "https://belly-johnny-carmen-jake.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products"

[auth]
redirect_urls = [
  "https://belly-johnny-carmen-jake.trycloudflare.com/auth/callback",
  "https://belly-johnny-carmen-jake.trycloudflare.com/auth/shopify/callback",
  "https://belly-johnny-carmen-jake.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://belly-johnny-carmen-jake.trycloudflare.com/sitemap"
subpath = "hubcodespace-sitemap-builder"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
